[package]
name = "web-basics-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
once_cell = "1.21.3"
yew = { version = "0.22.0", features= ["csr"] }
yew-autoprops = "0.4.1"
yew-interop = "0.3.0"
